### ISSUE TITLE
ckpt_path is not defined ERROR  

### ISSUE THREAD

**Issue by nishathussain** [researchmm/LightTrack#9]
what exactly is this path?
path_name=back_04502514044521042540+cls_211000022+reg_100000111_ops_32

On running:  bash tracking/reproduce_vot2019.sh

===> init Siamese <====
load pretrained model from snapshot/LightTrackM/LightTrackM.pth
Traceback (most recent call last):
  File "tracking/test_lighttrack.py", line 181, in <module>
    main()
  File "tracking/test_lighttrack.py", line 165, in main
    siam_net = load_pretrain(siam_net, args.resume)
  File "/home/nishat/adasi/tracking/LightTrack/tracking/../lib/utils/utils.py", line 702, in load_pretrain
    ckpt = torch.load(ckpt_path, map_location=lambda storage, loc: storage(device))    
NameError: name 'ckpt_path' is not defined
VOT2019
loading VOT2019: 100%|██████████████████████████████████| 60/60 [00:00<00:00, 61.31it/s, zebrafish1]
eval ar: 100%|████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.58it/s]
eval eao:   0%|                                                               | 0/1 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/nishat/miniconda3/envs/lighttrack/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/nishat/adasi/tracking/LightTrack/lib/eval_toolkit/bin/../../eval_toolkit/pysot/evaluation/eao_benchmark.py", line 47, in eval
    eao = self._calculate_eao(tracker_name, self.tags)
  File "/home/nishat/adasi/tracking/LightTrack/lib/eval_toolkit/bin/../../eval_toolkit/pysot/evaluation/eao_benchmark.py", line 110, in _calculate_eao
    max_len = max([len(x) for x in all_overlaps])
ValueError: max() arg is an empty sequence
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/eval_toolkit/bin/eval.py", line 148, in <module>
    trackers), desc='eval eao', total=len(trackers), ncols=100):
  File "/home/nishat/miniconda3/envs/lighttrack/lib/python3.6/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/nishat/miniconda3/envs/lighttrack/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
ValueError: max() arg is an empty sequence

**Comment by nishathussain** [comment]
While changing from CUDA to CPU, I did some mistake in utils.py,

**Comment by kk52099** [comment]
@nishathussain  i met the same problem,  do u solve it?

**Comment by kk52099** [comment]
@nishathussain  i met the same problem,  do u solver it?
